
export const CurtainsData = [{ 
    "status": "OK",
    "request_id": "97492a04-f7c9-4a08-be04-e88c190c9a6e",
    "data": {
        "total_products": 22386,
        "country": "US",    
        "domain": "www.amazon.com",
        "products": [ 
            {
                "asin": "B01CS31R94",
                "product_title": "NICETOWN Halloween Pitch Black Solid Thermal Insulated Grommet Blackout Curtains/Drapes for Bedroom Window (2 Panels, 42 inches Wide by 63 inches Long, Black)",
                "product_price": "$15.93",
                "unit_price": "$7.97",
                "unit_count": 2,
                "product_original_price": "$27.02",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 116104,
                "product_url": "https://www.amazon.com/dp/B01CS31R94",
                "product_photo": "https://m.media-amazon.com/images/I/61Xsz1yLEML._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$15.93",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11",
                "coupon_text": "Save 20% with coupon"
            },
            {
                "asin": "B015SJ7RYY",
                "product_title": "NICETOWN Gray Blackout Curtains for Bedroom 84 inches Long - Thermal Curtains &amp; Drapes Grommet Room Darkening Curtains Noise Reducing Window Treatments for Living Room (2 Panels, W52 x L84, Grey)",
                "product_price": "$18.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 49122,
                "product_url": "https://www.amazon.com/dp/B015SJ7RYY",
                "product_photo": "https://m.media-amazon.com/images/I/71XN5e+ZD+L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$18.98",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11",
                "coupon_text": "Save 10% with coupon"
            },
            {
                "asin": "B0881QG5WK",
                "product_title": "ChrisDowa Grommet Blackout Curtains for Bedroom and Living Room - 2 Panels Set Thermal Insulated Room Darkening Curtains (Dark Grey, 42 x 63 Inch)",
                "product_price": "$18.48",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 17474,
                "product_url": "https://www.amazon.com/dp/B0881QG5WK",
                "product_photo": "https://m.media-amazon.com/images/I/61b7ejuX+bS._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$18.48",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "7K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day",
                "coupon_text": "Save 20% with coupon"
            },
            {
                "asin": "B07D6HCZTY",
                "product_title": "BGment Blackout Curtains for Bedroom - Grommet Thermal Insulated Room Darkening Curtains for Living Room, Set of 2 Panels (42 x 63 Inch, Navy Blue)",
                "product_price": "$12.58",
                "unit_price": "$6.29",
                "unit_count": 2,
                "product_original_price": "$15.93",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 66719,
                "product_url": "https://www.amazon.com/dp/B07D6HCZTY",
                "product_photo": "https://m.media-amazon.com/images/I/61hCzv+DC5L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$12.58",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day"
            },
            {
                "asin": "B09QKMGXZM",
                "product_title": "NICETOWN Natural Linen Curtains 84 inch Long 2 Panels Set, Grommet Top Thick Linen Burlap Semi Sheer Vertical Drapes Privacy Assured with Light Filtering for Bedroom/Living Room, W55 x L84",
                "product_price": "$24.95",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 1328,
                "product_url": "https://www.amazon.com/dp/B09QKMGXZM",
                "product_photo": "https://m.media-amazon.com/images/I/815UWwMQCCL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$24.95",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day",
                "coupon_text": "Save 10% with coupon"
            },
            {
                "asin": "B07D39333V",
                "product_title": "Sun Zero Easton Energy Saving Blackout Grommet Curtain Panel, 40&quot; x 84&quot;, Sage Green",
                "product_price": "$10.27",
                "product_original_price": "$24.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 22747,
                "product_url": "https://www.amazon.com/dp/B07D39333V",
                "product_photo": "https://m.media-amazon.com/images/I/91DDjtynycL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$10.27",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "500+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day"
            },
            {
                "asin": "B08L4CJG4Z",
                "product_title": "NICETOWN White Sheer Linen Curtains for Living Room 84 inch Length 2 Panels Set, Grommet Semitransparent Balance Privacy &amp; Light Vertical Flax Sheer Drapes for Bedroom, W52 x L84",
                "product_price": "$13.53",
                "product_original_price": "$19.89",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 7634,
                "product_url": "https://www.amazon.com/dp/B08L4CJG4Z",
                "product_photo": "https://m.media-amazon.com/images/I/71+nAwkzbLL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$13.53",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11"
            },
            {
                "asin": "B01GCLYV5K",
                "product_title": "NICETOWN Halloween Black Blackout Curtain Blinds - Solid Thermal Insulated Window Treatment Blackout Drapes/Draperies for Bedroom (2 Panels, 42 inches Wide by 63 inches Long, Black)",
                "product_price": "$11.14",
                "product_original_price": "$15.93",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 39040,
                "product_url": "https://www.amazon.com/dp/B01GCLYV5K",
                "product_photo": "https://m.media-amazon.com/images/I/617bx1VnwXL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$11.14",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "4K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day"
            },
            {
                "asin": "B0BWDK5RNZ",
                "product_title": "Estelar Textiler Navy Blue and Greyish White Blackout Curtains for Bedroom 84 Inches Long, Full Room Darkening Grommet Curtains for Living Room,Thermal Insulated Ombre Drapes,52Wx84L,2 Panels",
                "product_price": "$35.99",
                "product_original_price": "$52.99",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 4161,
                "product_url": "https://www.amazon.com/dp/B0BWDK5RNZ",
                "product_photo": "https://m.media-amazon.com/images/I/710JIZe0yOL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$35.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 Or fastest delivery Tue, Jun 11 Arrives before Father's Day",
                "coupon_text": "Save 20% with coupon"
            },
            {
                "asin": "B0777WDF57",
                "product_title": "Exclusive Home Catarina Layered Solid Room Darkening Blackout and Sheer Grommet Top Curtain Panel Pair, 52&quot;x84&quot;, Rose Blush",
                "product_price": "$35.03",
                "unit_price": "$17.52",
                "unit_count": 2,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 15732,
                "product_url": "https://www.amazon.com/dp/B0777WDF57",
                "product_photo": "https://m.media-amazon.com/images/I/611+5Nnrg7L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$35.03",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "800+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 Or fastest delivery Tue, Jun 11",
                "coupon_text": "Save 5% with coupon"
            },
            {
                "asin": "B0B8CLCBS9",
                "product_title": "Sutuo Home Boho Curtains 84 Inches Long for Bedroom Living Room,Semi-Blackout French Country Linen Embroidery Vintage Chic Tassels Hollow Window Treatment Bohemian Drape, 1 Panel 52&quot; W x 84&quot; L, Blue",
                "product_price": "$28.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.8",
                "product_num_ratings": 231,
                "product_url": "https://www.amazon.com/dp/B0B8CLCBS9",
                "product_photo": "https://m.media-amazon.com/images/I/811CmoXSBpL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$28.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "50+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11",
                "coupon_text": "Save 10% with coupon"
            },
            {
                "asin": "B0B3546C2Q",
                "product_title": "OWENIE Sheer Curtains 84 inch Length, Ivory Sheer Cutains 2 Panels Set for Bedroom/Living Room, Rod Pocket Voile Fimly Sheer Drapes, 2pcs, Each 42&quot; W x 84&quot; L",
                "product_price": "$9.99",
                "unit_price": "$5.00",
                "unit_count": 2,
                "product_original_price": "$11.99",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 5039,
                "product_url": "https://www.amazon.com/dp/B0B3546C2Q",
                "product_photo": "https://m.media-amazon.com/images/I/81e71EV4VoL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day"
            },
            {
                "asin": "B08L4T6SYJ",
                "product_title": "HOMEIDEAS Sage Green Sheer Curtains 52 X 84 Inches Long 2 Panels Embroidered Leaf Pattern Pocket Faux Linen Floral Semi Sheer Voile Window Curtains/Drapes for Bedroom Living Room",
                "product_price": "$21.20",
                "unit_price": "$10.60",
                "unit_count": 2,
                "product_original_price": "$28.95",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 3326,
                "product_url": "https://www.amazon.com/dp/B08L4T6SYJ",
                "product_photo": "https://m.media-amazon.com/images/I/71s5XflfdZL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$21.20",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "400+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11",
                "coupon_text": "Save $2.00 with coupon"
            },
            {
                "asin": "B015KMICNE",
                "product_title": "NICETOWN Grey Blackout Patio Sliding Door Curtains 84 inch Length, Grommet Room Divider Thermal Insulated Curtain Drapes for French Door/Living Room (Gray, W100 x L84, 1 Panel)",
                "product_price": "$23.79",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 29805,
                "product_url": "https://www.amazon.com/dp/B015KMICNE",
                "product_photo": "https://m.media-amazon.com/images/I/71VvWAsgH0L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$23.79",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "700+ bought in past month",
                "delivery": "FREE delivery Sat, Jun 15 on $35 of items shipped by AmazonOr fastest delivery Tue, Jun 11 Arrives before Father's Day",
                "coupon_text": "Save 25% with coupon"
            }
        ]
    }
}]

export const ElectronicsData = [{
    "status": "OK",
    "request_id": "62ad48f5-5752-4e6f-9a6d-efb642e3150f",
    "data": {
        "total_products": 67907,
        "country": "US",
        "domain": "www.amazon.com",
        "products": [
            {
                "asin": "B0D12T4WZT",
                "product_title": "USB C Charger for iPhone 14 13 12 11 Charger, 3Pack 20W USB C Fast Charger Plug Power Adapter with 6FT Type C to L.ightning Cable for iPhone 14/13/12/11 Pro/Pro Max/XS Max/XS/XR/X/SE/8 and More",
                "product_price": "$15.99",
                "product_original_price": "$19.98",
                "currency": "USD",
                "product_star_rating": "4.9",
                "product_num_ratings": 86,
                "product_url": "https://www.amazon.com/dp/B0D12T4WZT",
                "product_photo": "https://m.media-amazon.com/images/I/61nKMuhlx7L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$15.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "8K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day",
                "coupon_text": "Save 30% with coupon"
            },
            {
                "asin": "B096SRYXMP",
                "product_title": "Beats Studio Buds - True Wireless Noise Cancelling Earbuds - Compatible with Apple &amp; Android, Built-in Microphone, IPX4 Rating, Sweat Resistant Earphones, Class 1 Bluetooth Headphones - White",
                "product_price": "$79.99",
                "product_original_price": "$149.95",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 89498,
                "product_url": "https://www.amazon.com/dp/B096SRYXMP",
                "product_photo": "https://m.media-amazon.com/images/I/41ijQEHFicS._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$79.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "7K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 Or fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0CWXNS552",
                "product_title": "Apple AirTag",
                "product_price": "$24.99",
                "product_original_price": "$29.00",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 703,
                "product_url": "https://www.amazon.com/dp/B0CWXNS552",
                "product_photo": "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$24.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B099VMT8VZ",
                "product_title": "Meta Quest 2 — Advanced All-In-One Virtual Reality Headset — 128 GB",
                "product_price": "$199.00",
                "product_original_price": "$249.99",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 73542,
                "product_url": "https://www.amazon.com/dp/B099VMT8VZ",
                "product_photo": "https://m.media-amazon.com/images/I/61GhF+JUXGL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$199.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "20K+ bought in past month",
                "delivery": "FREE delivery Jul 7 - Aug 5 Or fastest delivery Jul 5 - Aug 3"
            },
            {
                "asin": "B0CZ3TD6J2",
                "product_title": "Retractable Car Charger, 4 in 1 Fast Charging Car Charger 60W, 2 Retractable iPhone Charger Cables and USB Car Charger Compatible with iPhone 15/14/13/12/11 Pro Max",
                "product_price": "$23.99",
                "product_original_price": "$26.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 524,
                "product_url": "https://www.amazon.com/dp/B0CZ3TD6J2",
                "product_photo": "https://m.media-amazon.com/images/I/715jZKPvNPL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$23.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B09GJZKQ3K",
                "product_title": "JBL Flip 6 - Portable Bluetooth Speaker, powerful sound and deep bass, IPX7 waterproof, 12 hours of playtime, JBL PartyBoost for multiple speaker pairing for home, outdoor and travel (Blue)",
                "product_price": "$99.95",
                "unit_price": "$6.25",
                "unit_count": 16,
                "product_original_price": "$129.95",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 9630,
                "product_url": "https://www.amazon.com/dp/B09GJZKQ3K",
                "product_photo": "https://m.media-amazon.com/images/I/614f5R8ReXL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$99.95",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0C5MFHCLC",
                "product_title": "15FT Flat Extension Cord, Flat Plug Power Strip with USB C, Ultra Thin Flat Plug Extension Cord - 6 Outlets with 4 USB Ports(2 USB C Outlet), No Surge Protector for Dorm Room Travel Essentials",
                "product_price": "$22.99",
                "product_original_price": "$29.99",
                "currency": "USD",
                "product_star_rating": "4.8",
                "product_num_ratings": 699,
                "product_url": "https://www.amazon.com/dp/B0C5MFHCLC",
                "product_photo": "https://m.media-amazon.com/images/I/71JlYzKqc4L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$22.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0CXSTPWL5",
                "product_title": "Small Portable Charger for iPhone,Upgraded 5000mAh PD Fast Charging Power Bank,Mini Battery Pack Backup Charger Compatible with iPhone 14/14 Pro Max/13/13 Pro/12 Pro/11/XS/XR/X/8/7/6 etc-Black",
                "product_price": "$23.95",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 361,
                "product_url": "https://www.amazon.com/dp/B0CXSTPWL5",
                "product_photo": "https://m.media-amazon.com/images/I/61cAlFkKsyL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$23.95",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12",
                "coupon_text": "Save 15% with coupon"
            },
            {
                "asin": "B0CZPHPJLN",
                "product_title": "Beats Solo 4 - Wireless Bluetooth On-Ear Headphones, Apple &amp; Android Compatible, Up to 50 Hours of Battery Life - Slate Blue",
                "product_price": "$129.95",
                "product_original_price": "$199.95",
                "currency": "USD",
                "product_star_rating": "4.2",
                "product_num_ratings": 119,
                "product_url": "https://www.amazon.com/dp/B0CZPHPJLN",
                "product_photo": "https://m.media-amazon.com/images/I/510fGxoTsTL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$129.95",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "5K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 Or fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0D14VTV6C",
                "product_title": "iPhone Charger [Apple MFi Certified] 3Pack 10FT Long Lightning Cable Fast Charging Nylon Braided USB Cable iPhone Charger Cord Compatible with iPhone 14 13 12 11 Pro Max XR XS X 8 7 6 Plus SE, iPad",
                "product_price": "$7.99",
                "product_original_price": "$35.95",
                "currency": "USD",
                "product_star_rating": "5",
                "product_num_ratings": 28,
                "product_url": "https://www.amazon.com/dp/B0D14VTV6C",
                "product_photo": "https://m.media-amazon.com/images/I/718zKx890sL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$7.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "4K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day",
                "coupon_text": "Save 50% with coupon"
            },
            {
                "asin": "B0D4QHB4G1",
                "product_title": "iPhone 15 14 13 12 11 Charger Fast Charging USB C Charger Type C Charger Fast Charging [2-Pack] 6FT Cord for iPhone 15/15 Plus/15 Pro/15 Pro Max/iPhone 14/13/12/11/X/8/7/6/iPad Pro/Mini/AirPods",
                "product_price": "$9.90",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 87,
                "product_url": "https://www.amazon.com/dp/B0D4QHB4G1",
                "product_photo": "https://m.media-amazon.com/images/I/61bV4DbVAHL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.90",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "500+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0C58MS6HF",
                "product_title": "Anker Magnetic Power Bank 10,000mAh, Wireless Portable Charger, 20W Fast Charging Battery Pack with USB-C, Magsafe-Compatible with Magsafe,iPhone 15/15 Plus/15 Pro/15 Pro Max, iPhone 14/13/12 Series",
                "product_price": "$31.49",
                "product_original_price": "$39.99",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 5813,
                "product_url": "https://www.amazon.com/dp/B0C58MS6HF",
                "product_photo": "https://m.media-amazon.com/images/I/61RB59T7AFL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$31.49",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Thu, Jun 13"
            },
            {
                "asin": "B0D49CWPH2",
                "product_title": "USB C to USB C Cable, (5Pack 6FT), New Nylon USB C Charger Cable 60W(3A) for iPhone 15/15 Pro/15 Plus/15 Pro Max, iPad Mini 6/ Pro 2021, MacBook Pro 2020, Samsung Galaxy S23,Switch",
                "product_price": "$9.96",
                "product_original_price": "$29.77",
                "currency": "USD",
                "product_star_rating": "4.9",
                "product_num_ratings": 122,
                "product_url": "https://www.amazon.com/dp/B0D49CWPH2",
                "product_photo": "https://m.media-amazon.com/images/I/818ElRqqaJL._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.96",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Thu, Jun 13 Arrives before Father's Day",
                "coupon_text": "Save 50% with coupon"
            },
            {
                "asin": "B0D2NL9X6M",
                "product_title": "iPhone Charger 6 Pack (3/3/6/6/6/10ft) Apple MFi Certified Fast Charge Sync Lightning Cable Compatible with iPhone 14/13/12/11/Pro Max/SE/XR/XS/X/8/7 Plus iPad AirPods",
                "product_price": "$11.19",
                "product_original_price": "$11.99",
                "currency": "USD",
                "product_star_rating": "4.8",
                "product_num_ratings": 45,
                "product_url": "https://www.amazon.com/dp/B0D2NL9X6M",
                "product_photo": "https://m.media-amazon.com/images/I/61ryBbT3b0L._AC_SX444_SY639_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$11.19",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12",
                "coupon_text": "Save 40% with coupon"
            }
        ]
    }
}]

export const MensData = [{
    "status": "OK",
    "request_id": "e4959e3a-3dad-42bc-a092-323764c78fbb",
    "data": {
        "total_products": 7471,
        "country": "US",
        "domain": "www.amazon.com",
        "products": [
            {
                "asin": "B0B975F6TX",
                "product_title": "Viking Revolution Sea Salt Spray for Hair Men - Hair Texturizing Spray with Kelp, Aloe Vera and Red Algae Extract - Surf Spray to Add Volume and Texture Sea Salt Spray for Men Beach Hair Spray - 8oz",
                "product_price": "$9.88",
                "unit_price": "$1.24",
                "unit_count": 8,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 3779,
                "product_url": "https://www.amazon.com/dp/B0B975F6TX",
                "product_photo": "https://m.media-amazon.com/images/I/71UVAgMn5xL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.88",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "20K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day",
                "coupon_text": "Save 5% with coupon"
            },
            {
                "asin": "B09N1B6LL3",
                "product_title": "MINKINH Manicure Set Professional Nail Clipper Kit-26 Pieces Stainless Steel Manicure Kit,Nail Care Tools with Luxurious Travel Case",
                "product_price": "$9.99",
                "unit_price": "$9.99",
                "unit_count": 1,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 9762,
                "product_url": "https://www.amazon.com/dp/B09N1B6LL3",
                "product_photo": "https://m.media-amazon.com/images/I/812JNL02tAL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0BZWS5BM5",
                "product_title": "Under Armour Men&#x27;s Ignite Select Slide Sandal",
                "product_price": "$22.50",
                "product_original_price": "$30.00",
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 340,
                "product_url": "https://www.amazon.com/dp/B0BZWS5BM5",
                "product_photo": "https://m.media-amazon.com/images/I/313gAQSzZiL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$22.50",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "500+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B09W1R4JJ9",
                "product_title": "Force Factor Force Factor Test X180 Gummies Testosterone Booster for Men with Tongkat Ali, Horny Goat Weed, Tribulus Terrestris, Fenugreek, &amp; Black Maca, Supplement Men, Berry Punch, 60 Gummies, 1-Pack",
                "product_price": "$18.90",
                "unit_price": "$0.32",
                "unit_count": 59,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "3.9",
                "product_num_ratings": 1898,
                "product_url": "https://www.amazon.com/dp/B09W1R4JJ9",
                "product_photo": "https://m.media-amazon.com/images/I/81gIYeXtiIL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$18.90",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "6K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0BWTXV562",
                "product_title": "KALIYADI Polarized Sunglasses for Men, Lightweight Sun Glasses with UV Protection for Driving Fishing Golf",
                "product_price": "$15.98",
                "product_original_price": "$19.99",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 4462,
                "product_url": "https://www.amazon.com/dp/B0BWTXV562",
                "product_photo": "https://m.media-amazon.com/images/I/71nTlUeWD5L._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$15.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0B9DC2M89",
                "product_title": "Viking Revolution 4 Pack Mens Solid Colognes Men 0.5 Oz - Men Solid Perfume with Cedar Wood, Clary Sage, Vetiver, Sandalwood Cologne for Men - Balm Cologne for Mens Cologne Balm Travel Cologne Wax",
                "product_price": "$9.88",
                "unit_price": "$4.94",
                "unit_count": 2,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.2",
                "product_num_ratings": 4409,
                "product_url": "https://www.amazon.com/dp/B0B9DC2M89",
                "product_photo": "https://m.media-amazon.com/images/I/71VLZ5bmbQL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.88",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "4K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12",
                "coupon_text": "Save 5% with coupon"
            },
            {
                "asin": "B072QRN7HR",
                "product_title": "Hanes Men&#x27;s Ecosmart Fleece Sweatshirt, Cotton-blend Pullover, Crewneck Sweatshirt for Men, 1 Or 2 Pack Available",
                "product_price": "$9.80",
                "product_original_price": "$18.00",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 172747,
                "product_url": "https://www.amazon.com/dp/B072QRN7HR",
                "product_photo": "https://m.media-amazon.com/images/I/81D+bCgn8hL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.80",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0159XXTN2",
                "product_title": "Versace Men&#x27;s Designer Fragrance Sampler (8 count)",
                "product_price": "$20.98",
                "unit_price": "$41.96",
                "unit_count": 1,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "3.9",
                "product_num_ratings": 1867,
                "product_url": "https://www.amazon.com/dp/B0159XXTN2",
                "product_photo": "https://m.media-amazon.com/images/I/71IdM7t3MJL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$20.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "5K+ bought in past month",
                "delivery": "FREE delivery Jun 18 - 21 Or fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0787P86ZZ",
                "product_title": "Gildan Men&#x27;s Crew T-Shirts, Multipack, Style G1100",
                "product_price": "$19.97",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 289131,
                "product_url": "https://www.amazon.com/dp/B0787P86ZZ",
                "product_photo": "https://m.media-amazon.com/images/I/710o0VupScL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$19.97",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "8K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B08LTBLD95",
                "product_title": "Ultra Performance Mens 5 Pack Athletic Running Shorts, Basketball Gym Workout Shorts for Men with Zippered Pockets",
                "product_price": "$33.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4",
                "product_num_ratings": 5225,
                "product_url": "https://www.amazon.com/dp/B08LTBLD95",
                "product_photo": "https://m.media-amazon.com/images/I/713gy-qCC0L._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$33.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day",
                "coupon_text": "Save 5% with coupon (some sizes/colors)"
            },
            {
                "asin": "B01NAPQ4QP",
                "product_title": "DUDE Wipes Wipes - Flushable Wipes - 3 Pack, 144 Wipes - Unscented Extra-Large Adult Wet Wipes - Vitamin-E &amp; Aloe - Septic and Sewer Safe",
                "product_price": "$8.98",
                "unit_price": "$0.06",
                "unit_count": 150,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 144625,
                "product_url": "https://www.amazon.com/dp/B01NAPQ4QP",
                "product_photo": "https://m.media-amazon.com/images/I/71DfWn8yteL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$8.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "70K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0BV27DL6Y",
                "product_title": "COOFANDY Men&#x27;s Linen Shirts Short Sleeve Casual Shirts Button Down Shirt for Men Beach Summer Wedding Shirt",
                "product_price": "$25.58",
                "product_original_price": "$34.99",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 2004,
                "product_url": "https://www.amazon.com/dp/B0BV27DL6Y",
                "product_photo": "https://m.media-amazon.com/images/I/81+oQBvBR-L._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$25.58",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0016MNH7Y",
                "product_title": "Carhartt Men&#x27;s Loose Fit Heavyweight Short-Sleeve Pocket T-Shirt",
                "product_price": "$19.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 106303,
                "product_url": "https://www.amazon.com/dp/B0016MNH7Y",
                "product_photo": "https://m.media-amazon.com/images/I/61pyx+Tp-FL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$19.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0C9MBJ185",
                "product_title": "Showvigor Beard Bib Apron for Men, Gift Beard Trimming Catcher Bib for Shaving &amp; Hair Clippings, Waterproof Non-Stick Hair Catcher Grooming Cloth with 2 Suction Cups(White)",
                "product_price": "$8.88",
                "unit_price": "$8.88",
                "unit_count": 1,
                "product_original_price": "$9.99",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 3066,
                "product_url": "https://www.amazon.com/dp/B0C9MBJ185",
                "product_photo": "https://m.media-amazon.com/images/I/61laTwCEXwL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$8.88",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Thu, Jun 13"
            },
            {
                "asin": "B086LDXW63",
                "product_title": "Hanes Men&#x27;s Boxer Briefs, Soft and Breathable Cotton Underwear with ComfortFlex Waistband, Multipack",
                "product_price": "$21.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 145507,
                "product_url": "https://www.amazon.com/dp/B086LDXW63",
                "product_photo": "https://m.media-amazon.com/images/I/81C5dMaxWkL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$21.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "5K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B08K1PF2KK",
                "product_title": "HAPPY NUTS Comfort Cream Deodorant For Men: Anti-Chafing Sweat Defense, Odor Control, Aluminum-Free Mens Deodorant &amp; Hygiene Products for Men&#x27;s Private Parts 3.4 oz. (3.4 Fl Oz (Pack of 1), Unscented)",
                "product_price": "$15.00",
                "unit_price": "$4.41",
                "unit_count": 3,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 17143,
                "product_url": "https://www.amazon.com/dp/B08K1PF2KK",
                "product_photo": "https://m.media-amazon.com/images/I/51FIaQfykrL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$15.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0CMW64H59",
                "product_title": "Cremo Rich-Lathering Italian Bergamot Body Wash for Men, Notes of Italian Bergamot, Neroli Blossom, and Fresh Vetiver, 16 Fl Oz",
                "product_price": "$9.99",
                "unit_price": "$0.62",
                "unit_count": 16,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 4419,
                "product_url": "https://www.amazon.com/dp/B0CMW64H59",
                "product_photo": "https://m.media-amazon.com/images/I/61At90KdCaL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "8K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12",
                "coupon_text": "Save $1.20 with coupon"
            },
            {
                "asin": "B01FKP3Q7S",
                "product_title": "OLLY OLLY Men&#x27;s Multivitamin Gummy, Overall Health and Immune Support, Vitamins A, C, D, E, B, Lycopene, Zinc, Adult Chewable Vitamin, Blackberry, 45 Day Supply - 90 Count",
                "product_price": "$12.88",
                "unit_price": "$0.14",
                "unit_count": 92,
                "product_original_price": "$13.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 10181,
                "product_url": "https://www.amazon.com/dp/B01FKP3Q7S",
                "product_photo": "https://m.media-amazon.com/images/I/71oGoQigNhL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$12.88",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B07G263WT6",
                "product_title": "FITORY Men&#x27;s Flip-Flops, Thongs Sandals Comfort Slippers for Beach Size 6-15",
                "product_price": "$9.99",
                "product_original_price": "$29.99",
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 28308,
                "product_url": "https://www.amazon.com/dp/B07G263WT6",
                "product_photo": "https://m.media-amazon.com/images/I/71eRuRML3qL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "4K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0CNFTZSCK",
                "product_title": "Method Men Body Wash, Cedar + Cypress, Paraben and Phthalate Free, 18 fl oz (Pack of 1)",
                "product_price": "$7.98",
                "unit_price": "$0.44",
                "unit_count": 18,
                "product_original_price": "$9.19",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 87,
                "product_url": "https://www.amazon.com/dp/B0CNFTZSCK",
                "product_photo": "https://m.media-amazon.com/images/I/61dTbU-YozL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$7.98",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            }
        ]
    }
}]

export const WomenData = [{
    "status": "OK",
    "request_id": "0f0fba58-bb94-47cb-ad6f-fb1f592ec886",
    "data": {
        "total_products": 83387,
        "country": "US",
        "domain": "www.amazon.com",
        "products": [
            {
                "asin": "B0C4QD5VPB",
                "product_title": "Kristin Hannah The Women: A Novel",
                "product_price": "$0.00",
                "product_original_price": "$24.74",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 119638,
                "product_url": "https://www.amazon.com/dp/B0C4QD5VPB",
                "product_photo": "https://m.media-amazon.com/images/I/91mP3553EzL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": null,
                "delivery": null
            },
            {
                "asin": "B0CCVK7QXY",
                "product_title": "AOSTIHOT Crossbody Small Sling Backpack Sling Bag for Women Men, Chest Bag Daypack Crossbody for Travel Sport Running Hiking",
                "product_price": "$9.87",
                "product_original_price": "$11.95",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 1593,
                "product_url": "https://www.amazon.com/dp/B0CCVK7QXY",
                "product_photo": "https://m.media-amazon.com/images/I/61QAdTz6xxL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.87",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "700+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B07N3YKHNB",
                "product_title": "SOJOS Sunglasses Womens Trendy 2024 Classic Round Retro Vintage Shades Large Frame Sunnies SJ2067",
                "product_price": "$15.99",
                "product_original_price": "$19.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 33821,
                "product_url": "https://www.amazon.com/dp/B07N3YKHNB",
                "product_photo": "https://m.media-amazon.com/images/I/61a-ofc+rTS._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$15.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "9K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B08CZH461J",
                "product_title": "Amazon Essentials Women&#x27;s Cotton Bikini Brief Underwear (Available in Plus Size), Multipacks",
                "product_price": "$4.70",
                "product_original_price": "$6.60",
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 148339,
                "product_url": "https://www.amazon.com/dp/B08CZH461J",
                "product_photo": "https://m.media-amazon.com/images/I/81fp8+OI7rL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$4.70",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0C4H2YVPX",
                "product_title": "EASYFUN Lunch Bag for Women &amp; Men Adult Insulated Lunch Box, Small Leakproof Cooler Food Lunch Containers Reusable High Capacity Lunch Tote Bags for Work, Travel, Outdoor (Grey)",
                "product_price": "$9.99",
                "product_original_price": "$19.99",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 1636,
                "product_url": "https://www.amazon.com/dp/B0C4H2YVPX",
                "product_photo": "https://m.media-amazon.com/images/I/81J0YlRvgAL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "4K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0C1BJ6LVQ",
                "product_title": "CAMPSNAIL Biker Shorts Women with Pockets - 3&quot;/5&quot;/8&quot; High Waisted Workout Spandex Tummy Control Gym Running Yoga Shorts",
                "product_price": "$9.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 1369,
                "product_url": "https://www.amazon.com/dp/B0C1BJ6LVQ",
                "product_photo": "https://m.media-amazon.com/images/I/71FiFoe-7RL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "5K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0C38N41JX",
                "product_title": "ANRABESS Women 2 Piece Outfits Sweat Shorts Sets 2024 Oversized Casual Lounge Matching Set Sweatsuit Tracksuit Clothes",
                "product_price": "$36.99",
                "product_original_price": "$42.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 739,
                "product_url": "https://www.amazon.com/dp/B0C38N41JX",
                "product_photo": "https://m.media-amazon.com/images/I/71roJ-3hjBL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$36.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "800+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 Or fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B07K3STMJ4",
                "product_title": "Versace Miniature Variety Trio Collection Perfume Gift Set for Women",
                "product_price": "$23.16",
                "unit_price": "$45.41",
                "unit_count": 1,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 1012,
                "product_url": "https://www.amazon.com/dp/B07K3STMJ4",
                "product_photo": "https://m.media-amazon.com/images/I/61ribvoQdJL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$23.16",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Jun 18 - 20"
            },
            {
                "asin": "B08J5HLXRD",
                "product_title": "Elizabeth Crowley Prayer Journal For Women: 52 Week Scripture, Guided Prayer Notebook For Women Of God",
                "product_price": "$7.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 7584,
                "product_url": "https://www.amazon.com/dp/B08J5HLXRD",
                "product_photo": "https://m.media-amazon.com/images/I/71Xk0us8zjL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$7.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": null,
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B08ZSZKMZK",
                "product_title": "SOLY HUX Women&#x27;s Button Front Ribbed Knit Tank Top and Shorts Pajama Set Sleepwear Lounge Sets",
                "product_price": "$24.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 2429,
                "product_url": "https://www.amazon.com/dp/B08ZSZKMZK",
                "product_photo": "https://m.media-amazon.com/images/I/81OrEQKLINL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$24.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B08S482FV2",
                "product_title": "Under Armour Women&#x27;s Breathe Lite Ultra Low Socks, Multipairs",
                "product_price": "$16.50",
                "unit_price": "$2.75",
                "unit_count": 6,
                "product_original_price": "$22.00",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 9384,
                "product_url": "https://www.amazon.com/dp/B08S482FV2",
                "product_photo": "https://m.media-amazon.com/images/I/91UPqf-QBqL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$16.50",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "900+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Thu, Jun 13"
            },
            {
                "asin": "B0CF8LGK9L",
                "product_title": "ULTREAGLE Women&#x27;s Seamless No Show Thong Panties Comfortable Breathable Pack of 6 Underwear",
                "product_price": "$9.49",
                "product_original_price": "$19.99",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 655,
                "product_url": "https://www.amazon.com/dp/B0CF8LGK9L",
                "product_photo": "https://m.media-amazon.com/images/I/71MbrHUSvCL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.49",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "700+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12",
                "coupon_text": "Save 10% with coupon (some sizes/colors)"
            },
            {
                "asin": "B075YYK9NL",
                "product_title": "Nine West Women&#x27;s Crystal Accented Bracelet Watch",
                "product_price": "$17.62",
                "product_original_price": "$36.75",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 9795,
                "product_url": "https://www.amazon.com/dp/B075YYK9NL",
                "product_photo": "https://m.media-amazon.com/images/I/81-HbGIsxVL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$17.62",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B08SW7Q63Z",
                "product_title": "SOJOS Trendy Oversized Sunglasses for Women and Men",
                "product_price": "$14.99",
                "product_original_price": "$16.99",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 4110,
                "product_url": "https://www.amazon.com/dp/B08SW7Q63Z",
                "product_photo": "https://m.media-amazon.com/images/I/610PbBf2Y7L._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$14.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0BNH14LP3",
                "product_title": "Kacmagic 12 Pcs Rectangle Clips, Accessories for Women and Girls, Including 6 Pcs 4 Inch Large Clips for Thick Hair and 6 Pcs 2 inch Small Clips for Thin Hair (Neutral)",
                "product_price": "$5.39",
                "unit_price": "$0.45",
                "unit_count": 12,
                "product_original_price": "$5.99",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 3316,
                "product_url": "https://www.amazon.com/dp/B0BNH14LP3",
                "product_photo": "https://m.media-amazon.com/images/I/71fekV8VGNL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$5.39",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0CSK45Q6V",
                "product_title": "REORIA Women’s Sexy Sleeveless Square Neck Double Lined Bodysuit Tank Tops",
                "product_price": "$24.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 152,
                "product_url": "https://www.amazon.com/dp/B0CSK45Q6V",
                "product_photo": "https://m.media-amazon.com/images/I/61PO6gHq9sL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$24.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12",
                "coupon_text": "Save 20% with coupon (some sizes/colors)"
            },
            {
                "asin": "B0BGVZ75HW",
                "product_title": "Under Armour Women&#x27;s Fly by 2.0 Running Shorts",
                "product_price": "$12.86",
                "product_original_price": "$25.00",
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 24666,
                "product_url": "https://www.amazon.com/dp/B0BGVZ75HW",
                "product_photo": "https://m.media-amazon.com/images/I/51hWkGEzGTL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$12.86",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B016YKL60M",
                "product_title": "Hanes Women’s Slub Knit Full-Zip Hoodie, Textured Cotton Zip-Up T-Shirt Hoodie for Women",
                "product_price": "$14.00",
                "product_original_price": "$24.00",
                "currency": "USD",
                "product_star_rating": "4.2",
                "product_num_ratings": 52269,
                "product_url": "https://www.amazon.com/dp/B016YKL60M",
                "product_photo": "https://m.media-amazon.com/images/I/71AKVeHXVyL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$14.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            },
            {
                "asin": "B0C746QXL1",
                "product_title": "masatow Women Pheromone Perfume - Long-lasting and Addictive Personal Roll-on Pheromone Perfume Oil Fragrance - Cologne for Women to Attract Men (Pack of 2)",
                "product_price": "$9.99",
                "unit_price": "$14.91",
                "unit_count": 1,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "3.3",
                "product_num_ratings": 553,
                "product_url": "https://www.amazon.com/dp/B0C746QXL1",
                "product_photo": "https://m.media-amazon.com/images/I/61CqGvOdP3L._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12 Arrives before Father's Day"
            },
            {
                "asin": "B0874V9TV2",
                "product_title": "Under Armour Women&#x27;s HeatGear High No-Slip Waistband Ankle Leggings",
                "product_price": "$25.47",
                "product_original_price": "$45.00",
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 407,
                "product_url": "https://www.amazon.com/dp/B0874V9TV2",
                "product_photo": "https://m.media-amazon.com/images/I/41jSnMJUPeL._AC_SR525,789_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$25.47",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Mon, Jun 17 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jun 12"
            }
        ]
    }
}]